### ISSUE TITLE
Incorrect linter config

### ISSUE THREAD

**Issue by bolah2009** [misselliev/react-CMS-bookstore#4]
## Inncorrect linter config

The correct linter config for Stickler for react project is 

```yml
# add the linters you want stickler to use for this project
linters:
  eslint:
    # indicate where is the config file for stylelint
    config: './.eslintrc.json'

# PLEASE DO NOT enable auto fixing options
# if you need extra support from you linter - do it in your local env as described in README for this config

# find full documentation here: https://stickler-ci.com/docs
```

#### Not

https://github.com/misselliev/react-CMS-bookstore/blob/2a44787b3e91b26ae0612e32f498495e34605389/.stickler.yml#L1-L5

Let's create a `.eslintrc.json` file with the same content as in https://github.com/microverseinc/linters-config/blob/master/react-redux/.eslintrc.json

### Screenshots and Pathwright references

![image](https://user-images.githubusercontent.com/36057474/71924065-8b46a000-318e-11ea-8f37-02c188bde393.png)

Check https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/ for more details.
